version: '3'

volumes:
  redisdata:

services:
  postgres:
    container_name: auth-postgres
    image: postgres:alpine
    environment:
      POSTGRES_DB: "auth"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ../db-data/:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d auth" ] 
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
  
  migrate:
    container_name: auth-migrate
    image: migrate/migrate
    depends_on: 
      postgres:
        condition: service_healthy
    volumes:
      - ../migrations:/migrations
    command: 
      [ "-path", "/migrations", "-database",  "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@auth-postgres/auth?sslmode=disable", "up" ]

  redis:
    container_name: auth-redis
    image: redis:alpine
    command: >
      --requirepass ${REDIS_PASSWORD}
    volumes:
      - redisdata:/opt/redis/data
      - ../logs:/opt/redis/logs
    expose:
      - 6379
    healthcheck:
      test: redis-cli --no-auth-warning -a ${REDIS_PASSWORD} ping | grep PONG
      interval: 3s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  service:
    container_name: auth-service
    build:
      context: ..
      dockerfile: ./configs/dockerfiles/service.Dockerfile
      target: runner
    depends_on: 
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    volumes:
      - ../logs:/app/logs
    ports:
      - 8080:8080

  swagger-generator:
    container_name: auth-swagger-generator
    build:
      context: ..
      dockerfile: ./configs/dockerfiles/swagger_generator.Dockerfile
    volumes:
      - ../api:/app/api
    depends_on:
      - service

  swagger:
    container_name: auth-swagger
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: "/app/api/swagger.yaml"
    volumes:
      - ../api:/app/api
    ports:
      - 8000:8080
    depends_on:
      swagger-generator:
        condition: service_completed_successfully